include:
  - project: 'apc/common/gitlab-ci-utils'
    ref: refactor
    file: 'ci/scripts/gitlab-ci-susoft.yml'

##################
# LINUX BUILDS   #
##################

# Build all targets and run the tests
linux_build_and_test:
    extends: .linux_build_and_test

# Build and upload the libSpatialObjDLL.so
linux_release:
    extends: .linux_release
    needs: ["linux_build_and_test"]
    script:
        - echo "Building shared object library | -j$(nproc)"
        - $CMAKEBIN --build . -j $(nproc) --config Release --target SpatialObjDLL
        - cp staging/libSpatialObjDLL.so ..
    artifacts:
        name: sharedlibrary
        paths:
            - libSpatialObjDLL.so

##################
# WINDOWS BUILDS #
##################

# Build all targets and run the tests
windows64_build_and_test:
    extends: .windows64_build_and_test

# Build and upload the SpatialObjDLL.dll
windows64_release:
    extends: .windows64_release
    needs: ["windows64_build_and_test"]
    script:
        - echo "Building shared object library"
        - cmake --build . -j %NUMBER_OF_PROCESSORS% --config Release --target SpatialObjDLL
        - cp staging/SpatialObjDLL.dll ..
    artifacts:
        name: win64dll
        paths:
            - SpatialObjDLL.dll

# Build all targets and run the tests
windows32_build_and_test:
    extends: windows64_build_and_test
    tags:
        - windows
        - x32
    variables:
        CMAKEGENERATOR: "Visual Studio 16 2019"
        CMAKEARCHITECTURE: "-A Win32"

# Build and upload the SpatialObjDLL.dll
windows32_release:
    extends: windows64_release
    needs: ["windows32_build_and_test"]
    tags:
        - windows
        - x32
    variables:
        CMAKEGENERATOR: "Visual Studio 16 2019"
        CMAKEARCHITECTURE: "-A Win32"
    artifacts:
        name: win32dll
