/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SurveyLibJni */

#ifndef _Included_SurveyLibJni
#define _Included_SurveyLibJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SurveyLibJni
 * Method:    getCG2000N0_JNI
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG2000N0_1JNI
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     SurveyLibJni
 * Method:    getCG2000NMachine_JNI
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG2000NMachine_1JNI
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     SurveyLibJni
 * Method:    getCG1985N0_JNI
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG1985N0_1JNI
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     SurveyLibJni
 * Method:    getCG1985NMachine_JNI
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG1985NMachine_1JNI
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     SurveyLibJni
 * Method:    transformToMLA_JNI
 * Signature: ([DLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformToMLA_1JNI
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     SurveyLibJni
 * Method:    transformFromMLA_JNI
 * Signature: ([DLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformFromMLA_1JNI
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     SurveyLibJni
 * Method:    transformToMLA2_JNI
 * Signature: ([DLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformToMLA2_1JNI
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     SurveyLibJni
 * Method:    transformFromMLA2_JNI
 * Signature: ([DLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformFromMLA2_1JNI
  (JNIEnv *, jobject, jdoubleArray, jstring);

/*
 * Class:     SurveyLibJni
 * Method:    descenteVert_JNI
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_descenteVert_1JNI
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     SurveyLibJni
 * Method:    testFunction
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_testFunction
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif