/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class mardll1 */

#ifndef _Included_mardll1
#define _Included_mardll1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mardll1
 * Method:    simulation
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_mardll1_correction
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
