/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SurveyLibJni */

#ifndef _Included_SurveyLibJni
#define _Included_SurveyLibJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SurveyLibJni
 * Method:    getCG2000N0
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG2000N0
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     SurveyLibJni
 * Method:    getCG2000NMachine
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG2000NMachine
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     SurveyLibJni
 * Method:    getCG1985N0
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG1985N0
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     SurveyLibJni
 * Method:    getCG1985NMachine
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_getCG1985NMachine
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     SurveyLibJni
 * Method:    transformToMLA
 * Signature: (DDDDDDC)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformToMLA
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jchar);

/*
 * Class:     SurveyLibJni
 * Method:    transformFromMLA
 * Signature: (DDDDDDC)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformFromMLA
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jchar);

/*
 * Class:     SurveyLibJni
 * Method:    transformToMLA2
 * Signature: (DDDDDDC)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformToMLA2
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jchar);

/*
 * Class:     SurveyLibJni
 * Method:    transformFromMLA2
 * Signature: (DDDDDDC)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_transformFromMLA2
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jchar);

/*
 * Class:     SurveyLibJni
 * Method:    descenteVert
 * Signature: (DDDDDDD)I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_descenteVert
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     SurveyLibJni
 * Method:    testFunction
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SurveyLibJni_testFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
